version: "3.8"
services:
  site:
    image: jekyll/jekyll:4.2.0
    volumes:
      - .:/srv/jekyll
      - bundle:/usr/local/bundle
    ports:
      - 4000:4000
      - 35729:35729
    command: jekyll serve --livereload

volumes:
  bundle: {}
